CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(255) PRIMARY KEY,
  RESOURCE_IDS VARCHAR(255),
  CLIENT_SECRET VARCHAR(255),
  SCOPE VARCHAR(255),
  AUTHORIZED_GRANT_TYPES VARCHAR(255),
  WEB_SERVER_REDIRECT_URI VARCHAR(255),
  AUTHORITIES VARCHAR(255),
  ACCESS_TOKEN_VALIDITY INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONAL_INFORMATION VARCHAR(4096),
  AUTOAPPROVE VARCHAR(255)
);

CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY(255),
  AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255)
);

CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY(255),
  AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255),
  AUTHENTICATION VARBINARY(255),
  REFRESH_TOKEN VARCHAR(255)
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY(100),
  AUTHENTICATION VARBINARY(255)
);

CREATE TABLE OAUTH_CODE (
  CODE VARCHAR(255),
  AUTHENTICATION VARBINARY(255)
);

CREATE TABLE OAUTH_APPROVALS (
  USERID VARCHAR(255),
  CLIENTID VARCHAR(255),
  SCOPE VARCHAR(255),
  STATUS VARCHAR(10),
  EXPIRESAT TIMESTAMP,
  LASTMODIFIEDAT TIMESTAMP
);

/** FIM DA CRIACAO DO  AUTH**/

CREATE TABLE produtos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  data_exclusao DATETIME,
  idCategoria BIGINT NOT NULL,
  produto VARCHAR(255),
  preco double ,
  quantidade int(11) ,
  descricao VARCHAR(255),
  foto mediumblob,
  PRIMARY KEY (ID)
) ;


CREATE TABLE  categorias (
  id BIGINT NOT NULL AUTO_INCREMENT,
  data_exclusao DATETIME,
  categoria VARCHAR(50),
  status VARCHAR(50),
  sessao VARCHAR(255),
 
  PRIMARY KEY (ID)
) ;


CREATE TABLE  clientes (
  id BIGINT NOT NULL AUTO_INCREMENT,
  data_exclusao DATETIME,
  nome VARCHAR(50),
  email VARCHAR(255),
  senha VARCHAR(255),
  
  rua VARCHAR(255),
  cidade VARCHAR(255),
  bairro VARCHAR(255),
  cep VARCHAR(255),
  estado VARCHAR(255),
  PRIMARY KEY (ID)
) ;


CREATE TABLE  pedidos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  data_exclusao DATETIME,
  data datetime,
  idCliente BIGINT NOT NULL,
  status  VARCHAR(50),
  sessao VARCHAR(255),
 
  PRIMARY KEY (ID)
) ;



CREATE TABLE  pedidoItens (
  id BIGINT NOT NULL AUTO_INCREMENT,
  data_exclusao DATETIME,
  idPedido BIGINT NOT NULL,
  idProduto BIGINT NOT NULL,
  produto varchar(50),
  quantidade INTEGER,
  valor double,
  subtotal double,
  PRIMARY KEY (ID)
) ;
  

/** CRIACAO DE TABELA DE USUARIOS **/


CREATE TABLE autorizacao (

   ID BIGINT NOT NULL AUTO_INCREMENT,
   data_exclusao DATETIME,
   nome VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE autorizacao ADD CONSTRAINT nome UNIQUE(nome);


CREATE TABLE usuario (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  data_exclusao DATETIME,
  senha VARCHAR(255),
  username VARCHAR(255),
  contaExpirada BOOLEAN,
  acessoExpirado BOOLEAN,
  credencialExpirada BOOLEAN,
  ativo BOOLEAN,
  acesso_expirado BOOLEAN ,
  conta_expirada BOOLEAN ,
  credencial_expirada boolean,
  login VARCHAR(255),
  
  PRIMARY KEY (ID)
);


CREATE TABLE USUARIOS_AUTORIZACAO (
   usuario_id BIGINT NOT NULL,
   autorizacao_id BIGINT NOT NULL,
   PRIMARY KEY (usuario_id, autorizacao_id)
);



   ALTER TABLE USUARIOS_AUTORIZACAO ADD CONSTRAINT USUARIOS_AUTORIZACAO_AUTORIZACAO
   FOREIGN KEY (autorizacao_id) REFERENCES autorizacao(ID);

   ALTER TABLE USUARIOS_AUTORIZACAO ADD CONSTRAINT USUARIOS_AUTORIZACAO_USUARIO_
   FOREIGN KEY (usuario_id) REFERENCES usuario(id);
   
   


   
   
   ALTER TABLE produtos ADD CONSTRAINT FK_PRODUTOS_CATEGORIA
   FOREIGN KEY (idCategoria) REFERENCES categorias(id);
 
   
   ALTER TABLE pedidoItens ADD CONSTRAINT FK_PEDIDO_PRODUTOS
   FOREIGN KEY (idProduto) REFERENCES produtos(id);
   
   ALTER TABLE pedidoItens ADD CONSTRAINT FK_PEDIDO_ITENS_PEDIDOS
   FOREIGN KEY (idPedido) REFERENCES pedidos(id);
   
   ALTER TABLE pedidos ADD CONSTRAINT FK_Pedidos_Cliente
   FOREIGN KEY (idCliente) REFERENCES clientes(id);
   